server:
  port: 8081

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      port: 27017
      database: seriesFP
queue:
  series:
    name: "series-queue"